"""The Patristic Text Archive's scripture: Rahlfs, the SBLGNT and the Peshitta.

One repository, six corpora, and the split is not tidiness. ``pta9999`` holds 177 files
under six version tags, and the tags cut across the books rather than along them:
``pta-grc1`` is Rahlfs' Septuagint over the Old Testament and the SBL Greek New Testament
over the New; ``pta-syc1`` is the ETCBC Peshitta Old Testament and the Peshitta New
Testament beside it. **The licences change at the same seam** -- CC BY-SA and CC BY for
the Greek, CC BY-NC and CC BY for the Syriac -- so a corpus that spanned it could not
state what it was held under. Splitting at the Testament boundary means every corpus has
exactly one licence, and :func:`build` asserts it rather than assuming.

What this brings that the library did not have: **Rahlfs**, the critical Septuagint most
scholarship cites, where it held only Swete and Brenton; **Syriac**, a language it held
none of; and Greek text for ``1ES``, ``3MA``, ``4MA``, ``PSS`` and ``ODA``, which its
canon models and had no words for.

Which file is which book comes from ``data/tei_books.json``, generated by
``tools/gen_tei_books.py`` and keyed on the CTS URN rather than the work number -- because
``pta016`` is 1 Esdras in Greek and Ezra in Syriac, and a table that could not tell them
apart would put 456 verses in the wrong book.
"""

from __future__ import annotations

import json
from collections.abc import Iterator, Mapping
from functools import cache
from importlib import resources
from pathlib import Path
from typing import Final

from lxml import etree

from ..canon import is_known
from ..licences import Licence, get
from ..refs import VerseRef
from ..sources import BuiltCorpus, RemoteFile, Source
from .tei import cts_verses, read_licence

__all__ = ["SOURCE", "build"]

_RAW: Final = "https://raw.githubusercontent.com/PatristicTextArchive/pta_data/public/data"

#: What each corpus is: its label, the language it is written in, and the versification it
#: counts in.
#:
#: Measured, not assumed. Scoring chapter ends over the built corpora against every
#: shipped system::
#:
#:     rahlfs        1135 ch   org 82.2%   eng 74.4%   lxx 98.1%   vul 78.3%
#:     rahlfs-alt      49 ch   org 93.9%   eng 91.8%   lxx 97.3%   vul 64.3%
#:     sblgnt         260 ch   org 99.2%   eng 98.5%   lxx 99.2%   vul 96.5%
#:     peshitta-ot   1142 ch   org 94.4%   eng 84.3%   lxx 79.4%   vul 70.2%
#:     peshitta-nt    260 ch   org 98.8%   eng 99.6%   lxx 98.8%   vul 96.2%
#:
#: Rahlfs on ``lxx`` is no surprise -- that is what ``lxx`` describes -- and it wins by
#: sixteen points. The Peshitta Old Testament on ``org`` is the find: it is the first
#: witness to the pivot this library holds in a language other than Hebrew and Greek. The
#: decisive chapter is Genesis 31/32, where it has 54 verses and 33, the Hebrew division,
#: against the English tradition's 55 and 32.
#:
#: **The New Testament is declared ``org`` against the measurement, and here is why.** The
#: three chapters where it differs are 2 Corinthians 13 (14 verses, not 13), Acts 19 (41,
#: not 40) and Revelation 12 (17, where both systems say 18). The first two are verses the
#: Peshitta *has* and the critical Greek does not -- Byzantine fullness at the same verse
#: numbers, which is a fact about the text and not about its numbering. Declaring ``eng``
#: over two verses would route every ordinary citation of the Syriac New Testament through
#: the English system, and this repository has already settled that the same number over
#: different words is a text-type variant rather than a versification difference. The
#: 0.8% is also well inside the 5% margin at which ``ebible._reconcile`` would object.
CORPORA: Final[Mapping[str, tuple[str, str, str]]] = {
    "rahlfs": (
        "Septuaginta — Rahlfs 1935",
        "grc",
        "lxx",
    ),
    "rahlfs-alt": (
        "Septuaginta — Rahlfs 1935, the second text where he prints two",
        "grc",
        "lxx",
    ),
    "sblgnt": (
        "SBL Greek New Testament",
        "grc",
        "org",
    ),
    "peshitta-ot": (
        "Peshitta Old Testament — ETCBC",
        "syc",
        "org",
    ),
    "peshitta-nt": (
        "Peshitta New Testament",
        "syc",
        "org",
    ),
    "peshitta-alt": (
        "Peshitta — the second recension where two survive",
        "syc",
        "org",
    ),
}

#: Notes worth carrying into the built corpus, because they are things a reader of the
#: verses would otherwise have to find out the hard way.
NOTES: Final[Mapping[str, str]] = {
    "rahlfs-alt": (
        "Rahlfs prints two texts of Judges, Daniel, Susanna and Bel because they diverge "
        "too far to conflate, and Tobit twice for the same reason. This is the second of "
        "each. Which of a pair is Theodotion and which the Old Greek is not stated in the "
        "files and is not claimed here."
    ),
    "peshitta-alt": (
        "Second recensions: the Prayer of Manasseh, Tobit and 1 Maccabees each survive in "
        "Syriac in two forms, and the apocryphal psalms in three."
    ),
    "sblgnt": (
        "The text is the SBL Greek New Testament. The archive's files declare CC BY 4.0; "
        "the edition's own terms are not CC BY and do not permit redistribution, so those "
        "are what this corpus is recorded under. Both appear in its licence list."
    ),
    "peshitta-ot": (
        "CC BY-NC: this may not be used commercially, unlike the Peshitta New Testament "
        "beside it in the same repository."
    ),
}


@cache
def books() -> Mapping[str, Mapping[str, str | None]]:
    """The generated URN → book table."""
    path = resources.files("biblereference").joinpath("data", "tei_books.json")
    with path.open(encoding="utf-8") as handle:
        loaded: dict[str, dict[str, dict[str, str | None]]] = json.load(handle)
    return loaded["pta"]


def _wanted() -> list[tuple[str, str, str, str]]:
    """``(urn, filename, book, corpus)`` for every file worth fetching, in order."""
    out = []
    for urn, row in sorted(books().items()):
        book, corpus = row.get("book"), row.get("corpus")
        if book is None or corpus is None or not is_known(book):
            continue  # recorded in the table with book: null, and visible there
        out.append((urn, str(row["file"]), book, corpus))
    return out


def _files() -> tuple[RemoteFile, ...]:
    """One flat, uniquely-named file per book.

    Flat because ``library_digest`` matches an archived path against these names and
    ``fetch_source`` checks them to decide whether the source is already present. Both
    handle a nested name now, but a flat one cannot be got wrong.
    """
    return tuple(
        RemoteFile(url=f"{_RAW}/pta9999/{urn.split('.')[0]}/pta9999.{urn}.xml", name=name)
        for urn, name, _, _ in _wanted()
    )


def build(archive: Path) -> Iterator[BuiltCorpus]:
    """Parse the archive into one corpus per (edition, Testament)."""
    verses: dict[str, list[tuple[VerseRef, str]]] = {}
    licences: dict[str, set[Licence]] = {}
    notes: dict[str, list[str]] = {}
    missing: list[str] = []

    for urn, name, book, corpus in _wanted():
        path = archive / name
        if not path.exists():
            missing.append(name)
            continue
        tree = etree.parse(str(path))
        found = read_licence(path)
        if found is None:
            notes.setdefault(corpus, []).append(f"{urn}: declares no licence this library knows")
        else:
            licences.setdefault(corpus, set()).add(found)
        rows = verses.setdefault(corpus, [])
        for chapter, verse, subverse, text in cts_verses(tree):
            rows.append((VerseRef(book, chapter, verse, subverse), text))

    for corpus, rows in sorted(verses.items()):
        label, language, versification = CORPORA[corpus]
        seen = licences.get(corpus, set())
        if len(seen) > 1:
            # The Testament split exists precisely so this cannot happen. If it ever does,
            # the upstream has moved the seam and the corpora need re-cutting -- so say
            # which files disagree rather than quietly taking the strictest.
            raise ValueError(
                f"{corpus} was built from files under more than one licence "
                f"({', '.join(sorted(licence.id for licence in seen))}); the corpus split "
                f"in corpora/pta.py no longer matches the archive"
            )
        licence = next(iter(seen), None)
        if corpus == "sblgnt" and licence is not None:
            # The files declare CC BY 4.0. The text is the SBL Greek New Testament, whose
            # own terms are not CC BY and do not permit redistribution, so *that* is what
            # governs and what gets stored -- answering with the header would tell a user
            # they may do something they may not. Both are kept in `licences`, so the
            # discrepancy is visible in `doctor` rather than smoothed away.
            seen = {licence, get("sblgnt")}
            licence = get("sblgnt")
        own = list(notes.get(corpus, []))
        if corpus in NOTES:
            own.insert(0, NOTES[corpus])
        if missing:
            own.append(f"{len(missing)} declared file(s) absent from the archive")
        yield BuiltCorpus(
            id=corpus,
            label=label,
            language=language,
            versification=versification,
            verses=rows,
            notes=own,
            licence=licence,
            licences=tuple(sorted(seen, key=lambda item: item.id)),
        )


SOURCE: Final = Source(
    id="pta",
    label="Patristic Text Archive — scripture",
    homepage="https://github.com/PatristicTextArchive/pta_data",
    license=(
        "Varies by file and is read from each one: CC BY-SA 4.0 over Rahlfs' Old "
        "Testament, CC BY 4.0 over the Greek and Syriac New Testaments, CC BY-NC 4.0 over "
        "the Peshitta Old Testament."
    ),
    files=_files(),
    build=lambda archive: build(archive),
    note=(
        "Six corpora, cut at the Testament boundary because that is where both the "
        "edition and the licence change."
    ),
)
